'use server';

/**
 * @fileOverview An AI Tutor that can answer a student's questions.
 *
 * - aiTutor - A function that provides an answer to a given question.
 * - AiTutorInput - The input type for the aiTutor function.
 * - AiTutorOutput - The return type for the aiTutor function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AiTutorInputSchema = z.object({
  question: z.string().describe('The question asked by the student.'),
});
export type AiTutorInput = z.infer<typeof AiTutorInputSchema>;

const AiTutorOutputSchema = z.object({
  answer: z.string().describe('The answer generated by the AI tutor.'),
});
export type AiTutorOutput = z.infer<typeof AiTutorOutputSchema>;

export async function aiTutor(input: AiTutorInput): Promise<AiTutorOutput> {
  return aiTutorFlow(input);
}

const prompt = ai.definePrompt({
  name: 'aiTutorPrompt',
  input: {schema: AiTutorInputSchema},
  output: {schema: AiTutorOutputSchema},
  prompt: `You are an expert AI Tutor for students. Your role is to provide clear, concise, and helpful answers to their questions.

  A student has asked the following question:
  "{{{question}}}"

  Please provide a well-structured and easy-to-understand answer. If the question is complex, break it down into smaller parts. Use examples or analogies where appropriate to help with understanding.
  `,
});

const aiTutorFlow = ai.defineFlow(
  {
    name: 'aiTutorFlow',
    inputSchema: AiTutorInputSchema,
    outputSchema: AiTutorOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
